# Generated by Django 2.2.4 on 2021-09-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_task'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='helpers',
            field=models.ManyToManyField(related_name='colaborations', to='users.User'),
        ),
    ]
