# Generated by Django 2.2.4 on 2021-09-15 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
